### ISSUE TITLE
Compiling under Mac OSX  #include <malloc.h> error

### ISSUE THREAD

**Issue by FredTacker** [iceman1001/proxmark3#11]
if i try to Compiling the standart iceman1001/proxmark3 reposity with homebrew under mac osx 10.10 the terminal tells me the following error:

cmdhfmfhard.c:33:10: fatal error: 'malloc.h' file not found
# include < malloc.h >

```
     ^
```

1 error generated.
make[1]: **\* [obj/cmdhfmfhard.o] Error 1
make: **\* [client/all] Error 2

could you maybe help me to solve this problem?

**Comment by iceman1001** [comment]
can you run  "uname" on a terminal ?

**Comment by iceman1001** [comment]
and you can test in cmdhfmfhard.c to change the malloc.h call to this:

```
#ifndef __APPLE__
    #include <malloc.h>
#endif
```

**Comment by iceman1001** [comment]
how did it got with this one?  If no answer, I'll close it.

**Comment by FredTacker** [comment]
i didn't had time to check it out yet sorry

**Comment by iceman1001** [comment]
Since I haven't heard more here, I'm closing it.
