### ISSUE TITLE
[enhancement] Scan proxmark3.log for HID cards and try them against reader

### ISSUE THREAD

**Issue by samturner3** [iceman1001/proxmark3#114]
### User Story: 
Today I wanted to get back into a building that I had previously used  ```lf search``` on a valid HID card for. I went to my logs but I had not enabled date logging so it was impossible to know which result was the correct one.

### Solution:
A script that scans through proxmark3.log looking for ```"HID Prox TAG ID:"``` and trying all the card numbers found similar to ```lf hid brute```

### Work done so far:
[https://github.com/samturner3/proxmark3/tree/HIDBruteFromLog](url)

created ```pullHID.c``` that extracts the FC and card number from proxmark3.log.
![screen shot 2017-06-20 at 11 21 36 pm](https://user-images.githubusercontent.com/14887388/27335927-6b253044-5611-11e7-90fd-b6c178bbed0f.png)
![screen shot 2017-06-20 at 11 37 34 pm](https://user-images.githubusercontent.com/14887388/27335946-7b64ae44-5611-11e7-99e3-c6a3dd7c4a47.png)

### To Do
* Fix up line 83 to further separate / get rid of '- Card'
* Delete duplicates 
* (Lots more ++ I only just started the file scan as a concept)
* Implement into a command to run the actual attempt (```sendTry(fmtlen, fc, cn, delay, bs)```)

## About
Any help would be great / feedback if you think this would be useful? I have hardly ever coded in c. ALso help would be appreciated as I don't have too much spare time these days.

EDIT: Would this be appropriate for a new command, or a script? Since it requires the proxmark to be attached to attempt the card number against reader. 
Or could the card numbers be loaded into the proxmark then used in standalone (depending on number of numbers to try).

**Comment by iceman1001** [comment]
hm,  why do you use c?   Why no make a simple lua script?  or python? 
The functionality is 
- read textfile
- grep "hid prox tag id"  (or custom filter text)
- print found rows
- close file

_What not even use grep?_

> grep "key found"  *.log 

Together with sort, uniq,  and you get less..
> grep "HID Prox" *.log | uniq | sort

**Comment by iceman1001** [comment]
Getting the intersting unique row values from the log file.   Put it in a shell-file.

>  grep "HID Prox TAG ID" *.log | awk '{ printf "Raw %4s | FC %4s %4s\n",$5, $13,$16 }' | sort | uniq

if you want to add this into a file with value pm3 commands for hid sim?  or something else,  then you modify the above accordingly.

if you want to run it from inside pm3-client,  just make a lua script which runs the shell file,  then opens your newly created file and sends row by row to core.console.   

you only need some imagination for these things.

**Comment by iceman1001** [comment]
close?
