### ISSUE TITLE
How to simulate Mifare Ultralight EV1?

### ISSUE THREAD

**Issue by BlackPaaanda** [iceman1001/proxmark3#118]
Hi, iceman

I've dumped the data of a ultralight EV1 (48 bytes) tag (hopefully it is the data) using "hf mfu dump" and i got 32*7 characters table by using "pm3_mfd2eml.py" function. However, when i try to use "hf mfu eload" to load this file to pm3's emulator memory, it said: ............File reading error. Did i do something wrong or how actually should i simulate the ultralight EV1 tag?

**Comment by iceman1001** [comment]
I know, its a known quirk   
The dump file needs to be 255 blocks... 
just add the extra needed empty blocks and it should Eload without problems.

**Comment by BlackPaaanda** [comment]
Does this means that the data table should be 32*255 with all extra blocks be empty?

**Comment by BlackPaaanda** [comment]
Hi iceman,

As i tried to modify the dump file, the proxmark3 can simulate the MF0UL11 tag.
However, i checked the .eml data, found that the first 4 blocks are all 0. Number starts to change at block 4 and it matches the card finger prints. What does that mean?

**Comment by iceman1001** [comment]
that has to do with the dump-file-format adds "special" data the first 48bytes. Afterwards comes the normal datablock.  I'm unsure if the eload/simulation takes this in consideration.  it should but I'ven't looked at it for a long time.

**Comment by iceman1001** [comment]
close ?

**Comment by BlackPaaanda** [comment]
Thanks a lot iceman. You can close this

Iceman <notifications@github.com>于2017年8月9日 周三16:08写道：
