### ISSUE TITLE
Tilde in legic.lua script

### ISSUE THREAD

**Issue by scaery** [iceman1001/proxmark3#122]
There might be some error in the imported or merged legic.lua

```
client/scripts/legic.lua:389: unexpected symbol near '~'
client/scripts/legic.lua:459: unexpected symbol near '~'
client/scripts/legic.lua:605: unexpected symbol near '~'
client/scripts/legic.lua:609: unexpected symbol near '~'
client/scripts/legic.lua:1360: unexpected symbol near '~'
client/scripts/legic.lua:1386: unexpected symbol near '~'
client/scripts/legic.lua:1703: unexpected symbol near '~'
client/scripts/legic.lua:2689: unexpected symbol near '~'
```

The origin is still here and working:
https://github.com/akileos/proxmark3/blob/bf413f1b871d3adae107ed03a5fbfd03a5e3603a/client/scripts/legic.lua

**Comment by iceman1001** [comment]
yeah,  thanks for issue,  it was something I introduced which was wrong.  I've commited a correction.  Should work better now.  Still different,  since the original script uses binary files as input...  
So this script will still have that issue.
