### ISSUE TITLE
missing Intratone key

### ISSUE THREAD

**Issue by fallen** [iceman1001/proxmark3#133]
https://github.com/iceman1001/proxmark3/blob/b6d68ec0aa3dec2cbfa009b61a52ef58540e0edc/client/default_keys.dic#L341
Hello, 
Is this on purpose that there is just *one* missing Intratone key? (Sector 5 B)
Do you want it?

**Comment by iceman1001** [comment]
I belive the list is from the linked page. I may have forgotten to paste the Sector 3 B,  but the 5B?

Feel free to add all your keys and make a PR. I'll merge it.

**Comment by fallen** [comment]
I confirm it's 5B, please see https://github.com/iceman1001/proxmark3/pull/134

**Comment by iceman1001** [comment]
You are too fast.  See my reason for closing it.

**Comment by iceman1001** [comment]
and the key was already in the file.  A bit further down.  Search for it and you find it.
