### ISSUE TITLE
Cross Compiling Error Arch Linux - unused-const-variable

### ISSUE THREAD

**Issue by ptu** [iceman1001/proxmark3#145]
I run into the following Errors while compiling firmware and bootrom:

```
../common/usb_cdc.c:264:19: error: 'StrOSDescriptor' defined but not used [-Werror=unused-const-variable=]
 static const char StrOSDescriptor[] = {
                   ^~~~~~~~~~~~~~~
../common/usb_cdc.c:160:19: error: 'OSFeatureDescriptor' defined but not used [-Werror=unused-const-variable=]
 static const char OSFeatureDescriptor[] = {
                   ^~~~~~~~~~~~~~~~~~~
```

Tried to compile from github, checked out `ice_v3.1.0` tag. Using arm-none-eabi-gcc 7.20 on Arch Linux.

Everything runs smooth when compiling from the proxmark3 repo in tag `3.0.1`

**Comment by iceman1001** [comment]
comment out,  they are not in use anymore.  Suggest you use latest source instead of tag.
Next release will be up in a few weeks.
