### ISSUE TITLE
hf 15 buggy (because of to much waiting)

### ISSUE THREAD

**Issue by lnv42** [iceman1001/proxmark3#157]
Hi
I'm experiencing  bugs with your version of armsrc/iso25693.c that seems to be related to too much waiting into TransmitTo15693Tag() and TransmitTo15693Reader() (added in commit : https://github.com/iceman1001/proxmark3/commit/823a814cf62a1c8290c19e1a219b5505a54b1012).
A lot of operations are failing (i saw that in my fork but i checked and it fail the same way on your's).
 This commit fixed it for me : https://github.com/lnv42/proxmark3/commit/84cb4f6bbf8811ba389cd5affa994d837f712894
I will do a PR when all my job on iso15 will be done and i'm not ready yet. But you maybe interested into CP this little commit sooner to fix this.

**Comment by iceman1001** [comment]
Excellent!

Already pushed ;)  
https://github.com/iceman1001/proxmark3/commit/5939164635a8b45b2d2f296a50c99020497878f7
