### ISSUE TITLE
hf mfdes authentication to an app (DesFire EV1)

### ISSUE THREAD

**Issue by jpclair** [iceman1001/proxmark3#165]
Hi,

I have a question regarding the command
```hf mfdes auth ```

With the Desfire EV1, when I have to read datas from an app:
1) select App
2) authenticate (with the key + crypto)
3) read datas (or write data with a write key)

Is there a way to reproduce that behavior with the mfdes auth command?

Thanks,

**Comment by iceman1001** [comment]
there is not much Desfire functionality implemented,   do feel free to contribute with adding read/write commands

**Comment by jpclair** [comment]
Ok thanks for your help. I'm a beginner in electronics, and in C. So I don't think I'm able to help to implement this kind of feature :)

**Comment by iceman1001** [comment]
A good challenge :)   you can do it!
