### ISSUE TITLE
[idea] Feature suggestion data directory parameter

### ISSUE THREAD

**Issue by ghost** [iceman1001/proxmark3#195]
It might be nice to have a config file Proxmark client can check for in the directory or a command line parameter to specify a default data directory for dumps, keyfiles, etc.  

proxmark3 --data=~/rfData
or 
a variable in a config.

1) It can help decrease the clutter a bit in the client directory.

2) I am switching between a couple forks,  it would be nice to keep all my different key files and dumps together.

I know I can do this manually by moving data around afterwards, using relative paths, or absolute paths.  It just might make it a bit nicer, especially for the docker image.

**Comment by iceman1001** [comment]
That is an execellent idea.

**Comment by iceman1001** [comment]
Hi Woody,
If you switch to RRG/Iceman repo,  you will find this is implemented. 
https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/path_notes.md
