### ISSUE TITLE
hf 14b SRI tag reading currently broken

### ISSUE THREAD

**Issue by elafargue** [iceman1001/proxmark3#205]
On git hash a7fd398d332e9b76 

SRI512 tag detection and reading is currently not working at all.

Did A/B test between master repo and your fork, and all SRI-related functions seem to be not working on your fork a the moment, so I though I'd tag this so that you can take a look in case you didn't know about it already?

**Comment by elafargue** [comment]
I also noticed that generic detection of 14b tags seems to be broken as well, which makes since since SRI tags use a 14b modulation. Tried with another 14b card (Swedish id card prototype) and it can be detected fine on main repo, but not at all on this fork.

**Comment by iceman1001** [comment]
yup, yup,   14b suffers at the moment.  

Tried to adapt it to the  **hf 14b reader/info/dump/restore/raw** pattern,  but so little time to finish it.

Feel free to contribute!

**Comment by iceman1001** [comment]
yup, yup,   14b suffers at the moment.

**Comment by iceman1001** [comment]
hf 14b reader works again.
