### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pabb85** [iceman1001/proxmark3#215]
Hi there,

Sorry if this is answered elsewhere but I have done a fair amount of searching for documentation on the following topics and I am finding it fairly sparse;

Offline usage of the device - as a simulator, to perform reader attacks, automatic mifare cloning?
The different modes of the device - A,B,C,D - switching between them and what they each do?

Connected via USB it works great but I feel like I'm missing out on some of the great features here and I would like to know more about them.

Cheers,
P.

**Comment by iceman1001** [comment]
Try searching for standalone modes on forum,  google,  wiki.   
The individual standalone modes are custom built and not offical documents exits. You will need to find the original author and see what kind of documentation there is.

**Comment by pabb85** [comment]
Thank you - happy for this to be closed... It is a question.  Where would you suggest looking / or people to speak to about it?  I have searched google, forums, also nothing on the wiki.

**Comment by rdfierro** [comment]
I'd like to echo this, Iceman.  I have been looking for instruction repositories for standalone on the Wiki, but to no avail.  I think it would be extremely helpful if documentation around this subject were housed there as I think this is becoming a more popular testing platform

**Comment by iceman1001** [comment]
This is the codebase issues page,  if you want to have discussions turn to the forum.
