### ISSUE TITLE
[Question] Does this build work with the ELECHOUSE Proxmark3 V2?

### ISSUE THREAD

**Issue by dylangerdaly** [iceman1001/proxmark3#229]
Hello,

Apologies if this is a bad Question, does anyone know if this build would work with the ELECHOUSE Proxmark3 V2?

I want a more portable PM3, but with Iceman's build.

It's running a AT91SAM7S512 MCU, not sure if there are any build flags or anything I need to set during compile time, or if it's just flat-out not compatible.

Cheers!

**Comment by iceman1001** [comment]
Should work out the box.

**Comment by joanbono** [comment]
I can confirm, it works.

**Comment by iceman1001** [comment]
If you edit the makefiles,   and remove  -DWITH_SMARTCARD ,  -DWITH_FLASH   you shouldn't get those functions since they are only rvd40.

**Comment by dylangerdaly** [comment]
Thank you all! It's on it's way! 😃
