### ISSUE TITLE
Can't run amiibo lua script

### ISSUE THREAD

**Issue by axfla** [iceman1001/proxmark3#235]
Hi
Running amiibo lua script resulted in "libcrypto.so.1.0.0 cannot open shared object file no such file or directory", so I had to downgrade to libssl1.0.0 in order to get this old shared library.
I am now facing "./libluamiibo.so: undefined symbol: lua_createtable" when trying to run it and have no clue on how to fix it. Is the amiibo script deprecated, or should it still work ?
Thanks

**Comment by iceman1001** [comment]
nay,  its just merged from james repo,  however his repo has another setting in his client makefile which allows for dynamic loading of libs. 
you find it here:
https://github.com/nccgroup/proxmark3-amiimicyou/blob/master/client/Makefile#L162

I didn't get it to compile on mingw, so feel free to fix it.

**Comment by axfla** [comment]
Adding -rdynamic to your makefile did the trick.
Replacing arg1 value to "7" was necessary too, because 6 no longer refers to NTAG215. https://github.com/iceman1001/proxmark3/blob/master/client/scripts/amiibo.lua#L88
The result was not as intended when tested with the nintendo switch or a smartphone reader though, but I will open a thread on the forum about that with some questions :smile:

Thank you for support

**Comment by iceman1001** [comment]
he also has a different view on bigbuff memory,  so it will need adaptations on it.
To eload it up,  don't need all reads like he did it.
