### ISSUE TITLE
Fixed problem samyrun, but is it a good fix?

### ISSUE THREAD

**Issue by DidierStevens** [iceman1001/proxmark3#239]
I could not get samyrun on my new RDV4 to read HID cards.

I Debugged it: the card is never read because signalprop.isnoise is always TRUE.

My fix: in common/lfdemod.c, line 1892, replace
    if (signalprop.isnoise) return -2;
with
    if (justNoise(dest, *size)) return -2;

Now I can read HID cards in standalone mode.

But is this a good fix? Because I compared with the Proxmark repository, and this function (HIDdemodFSK) has changed significantly.
Is it better to copy that new function?

**Comment by TomHarkness** [comment]
Nice Find! @iceman1001 and I were talking about this yesterday. What do you think?

**Comment by TomHarkness** [comment]
Confirmed - working for all LF Stand Alone modes. Just looking to see if this broke anything else.

**Comment by iceman1001** [comment]
Cool!  I believe the guys behind project walrus mentioned this fix some weeks ago.   Thought that they were going to push PR.   This fixes the current problem.

**Comment by iceman1001** [comment]
I pushed fixes into RRG repo.

**Comment by iceman1001** [comment]
@DidierStevens   If you use the  RRG repo instead,  that will bring more functionality to your RDV40. 
Among other this fix for LF standalone. and many more.

**Comment by osysltd** [comment]
@iceman1001 can you please share the link to RRG repo?

**Comment by iceman1001** [comment]
Of course.
https://github.com/RfidResearchGroup/proxmark3

**Comment by DidierStevens** [comment]
Thanks!

**Comment by iceman1001** [comment]
@DidierStevens   does the standalone work for you now?  time to close?

**Comment by DidierStevens** [comment]
@iceman1001  I'll check tomorrow.
So the fix is in the RRG repo now?
Isn't the default standalone HF in that repo?

**Comment by iceman1001** [comment]
@DidierStevens  its quite easy to swap which standalone that compiles in that repo now.
Only one line change in armsrc/makefile.    Don't let that stop you.

**Comment by DidierStevens** [comment]
The standalone in that repo works for me.

The line I had to change was in common/Makefile_Enabled_Options.common:
APP_CFLAGS += -DWITH_ISO14443a_StandAlone \
