### ISSUE TITLE
Suggestion: new client command rem (remark) - can do PR

### ISSUE THREAD

**Issue by DidierStevens** [iceman1001/proxmark3#241]
I like to refer to the proxmark3.log file to find back data.
To help me with this, I added a rem (remark) command to the client.
This command echoes its arguments, together with a timestamp, like this:

command: rem Library card
output: 2018-09-02T08:26:02Z remark: Library card

This gives me more context when I search through the proxmark3.log

If you are interested in this new command, I'll do a PR.

![image](https://user-images.githubusercontent.com/6815601/44954241-3f4f6100-ae9f-11e8-9a26-fefa86d90f2a.png)

**Comment by iceman1001** [comment]
cool,   I can see that it might help out for ppl who parses the log file.

**Comment by DidierStevens** [comment]
Cool! Did a PR.
