### ISSUE TITLE
[idea] mifare classic run hardnested against all unknown blocks and dump keys to file

### ISSUE THREAD

**Issue by thesle3p** [iceman1001/proxmark3#257]
Unless I am missing something the hardnested attack is not able to dump the keys it finds to a bin file the way the regular nested attack can, Also it would be extremely useful if we could have it target all the unknown keys/blocks on the card the way we can with the regular nested attack.

**Comment by iceman1001** [comment]
[executing the improved hardnested attack](https://youtu.be/tUZHtUJerJY)

**Comment by iceman1001** [comment]
Added to rrg/iceman repo.   **hf mf autopwn**

https://github.com/RfidResearchGroup/proxmark3/pull/353
