### ISSUE TITLE
Sniffing data format

### ISSUE THREAD

**Issue by zhangziran** [iceman1001/proxmark3#260]
Try to perform hf 14a sniff sniffing using iceman firmware，But the format is different from the official, I hope to get help.

**The following is the official firmware format**
 +  50782:    :     26
 +  33822:    :     26
 +  50422:    :     26
 +     64:   0: TAG 04  00
 +    944:    :     93  20
 +     64:   0: TAG 9c  59  9b  32  6c
 +   1839:    :     93  70  9c  59  9b  32  6c  6b  30
 +     64:   0: TAG 08  b6  dd
 +   3783:    :     60  32  64  69
 +    113:   0: TAG 82  a4  16  6c
 +   1287:    :     a1  e4  58  ce  6e  ea  41  e0
 +     64:   0: TAG 5c  ad  f4  39

Execute ./mfkey64 9c599b32 82a4166c a1e458ce 6eea41e0 5cadf439 to decrypt

**The following is the iceman firmware format**

pm3 --> hf 14a sniff          
#db# Starting to sniff          
pm3 --> hf 14a list          
trace pointer not allocated
#db# maxDataLen=160, Uart.state=0, Uart.len=0          
#db# traceLen=4347, Uart.output[0]=00000000          
Recorded Activity (TraceLen = 4347 bytes)          
          
Start = Start of Start Bit, End = End of last modulation. Src = Source of Transfer          
iso14443a - All times are in carrier periods (1/13.56Mhz)          
          
      Start |        End | Src | Data (! denotes parity error)                                           | CRC | Annotation          
------------+------------+-----+-------------------------------------------------------------------------+-----+--------------------          
          0 |       2368 | Tag |04  00                                                                   |     |           
     182288 |     184656 | Tag |04  00                                                                   |     |           
     203408 |     209296 | Tag |26  36  e5  58  ad                                                       |     |           
     235040 |     238560 | Tag |08  b6  dd                                                               |     |           
    2943472 |    2945840 | Tag |04  00                                                                   |     |           
    2964464 |    2970352 | Tag |26  36  e5  58  ad                                                       |     |           
    2996224 |    2999744 | Tag |08  b6  dd                                                               |     |           
    5704224 |    5706592 | Tag |04  00                                                                   |     |           
    5725216 |    5731104 | Tag |26  36  e5  58  ad                                                       |     |           
    5756848 |    5760368 | Tag |08  b6  dd                                                               |     |           
    8614640 |    8617008 | Tag |04  00                                                                   |     |           
    8805040 |    8807408 | Tag |04  00                                                                   |     |           
    8826160 |    8832048 | Tag |26  36  e5  58  ad                                                       |     |           
    8857888 |    8861408 | Tag |08  b6  dd                                                               |     |           
    8899120 |    8903792 | Tag |01  b0  81  e7                                                           |     |           
    8919856 |    8924592 | Tag |ca  96  05  d6                                                           |     |           
    8949280 |    8970144 | Tag |77  f8  56! 3b! 93  46  e2! c6  a4! a4! c0  2c! 4f! 4c! 9f! bd! 35! 4c   | !crc|           
    8989840 |    9010704 | Tag |7e  3a  27  ae  7c! 6f! 8d  07  28! 45! 5d! 6f  25  09  88  5d  dd  5d   | !crc|           
    9030432 |    9051296 | Tag |d3  5a! 04  95  d2  59! d9! 98! d1! a5  6e! 8b! 85! 45! a1! a7! f9! 32   | !crc|           
    9241472 |    9243840 | Tag |04  00                                                                   |     |           
    9431952 |    9434320 | Tag |04  00                                                                   |     |           
    9452944 |    9458832 | Tag |26  36  e5  58  ad                                                       |     |           
  149273728 |  149276096 | Tag |04  00                                                                   |     |           
  149455616 |  149457984 | Tag |04  00                                                                   |     |           
  149476608 |  149482496 | Tag |26  36  e5  58  ad                                                       |     |           
  152182736 |  152185104 | Tag |04  00                                                                   |     |           
  152203728 |  152209616 | Tag |26  36  e5  58  ad                                                       |     |           
  154920384 |  154922752 | Tag |04  00                                                                   |     |           
  154941360 |  154947248 | Tag |26  36  e5  58  ad                                                       |     |           
  154973104 |  154976624 | Tag |08  b6  dd                                                               |     |           
  157820176 |  157822544 | Tag |04  00                                                                   |     |           
  158010512 |  158012880 | Tag |04  00                                                                   |     |           
  158031632 |  158037520 | Tag |26  36  e5  58  ad                                                       |     |           
  158063248 |  158066768 | Tag |08  b6  dd                                                               |     |           
  158104448 |  158109184 | Tag |88  0f  e7  15                                                           |     |           
  158125312 |  158130048 | Tag |d0  66  38  e3                                                           |     |           
  158154752 |  158175616 | Tag |28! e7! dc! 80! 6f  a0! b2  fb! c2! 56! 07  75! 41! 09! f2  d9! 4c  32   | !crc|           
  158195328 |  158216128 | Tag |68! 52  a4  c5  05  75! b4  b3  56! fd! a9  2d  4d  d8  e8! 8c! da! 03   | !crc|           
  158235904 |  158256704 | Tag |ef! f7  62! 2a! 94  60  fe! 98  8e! bb! f1! b5! 7c  34! bf  4a! 4d! d4   | !crc|           
  158446896 |  158449264 | Tag |04  00                                                                   |     |           
  158637408 |  158639776 | Tag |04  00                                                                   |     |           
  158658400 |  158664288 | Tag |26  36  e5  58  ad                                                       |     |           
  158690144 |  158693664 | Tag |08  b6  dd                                                               |     |           
  158731360 |  158736096 | Tag |96  05  6d  8c                                                           |     |           
  158752096 |  158756768 | Tag |9d  b1! 2d  0b!                                                          |     |           
  158781520 |  158802320 | Tag |7a! be! 1e! a0  c2  1f! aa! fa! 16! c4! 1b  6e  9b! 27! ec! b8! 09! 8c!  | !crc|           
  158822096 |  158842960 | Tag |9c  fa! 40  31! 78  22! 2e  cc  36! 96! 26! 69! 40  7d  8c  ae! b8  1e!  | !crc|           
  158862672 |  158883472 | Tag |c2  35! f3  03! 27  3c! 1d! ea! a6  3d! 61  57! 7a! 5a  e9! 5a! b5! 42   | !crc|           
  317245952 |  317248320 | Tag |04  00                                                                   |     |           
  317427904 |  317430272 | Tag |04  00                                                                   |     |           
  317449024 |  317454912 | Tag |26  36  e5  58  ad                                                       |     |           
  317480640 |  317484160 | Tag |08  b6  dd                                                               |     |           
  320188832 |  320191200 | Tag |04  00                                                                   |     |           
  320209952 |  320215840 | Tag |26  36  e5  58  ad                                                       |     |           
  320241568 |  320245088 | Tag |08  b6  dd                                                               |     |           
  322949824 |  322952192 | Tag |04  00                                                                   |     |           
  322970944 |  322976832 | Tag |26  36  e5  58  ad                                                       |     |           
  323002544 |  323006064 | Tag |08  b6  dd                                                               |     |           
  325849856 |  325852224 | Tag |04  00                                                                   |     |           
  326040272 |  326042640 | Tag |04  00                                                                   |     |           
  326061264 |  326067152 | Tag |26  36  e5  58  ad                                                       |     |           
  326093008 |  326096528 | Tag |08  b6  dd                                                               |     |           
  326134336 |  326139072 | Tag |41  d7  c3  46                                                           |     |           
  326155072 |  326159744 | Tag |78! f9! 7c! 0d!                                                          |     |           
  326184512 |  326205376 | Tag |4f  9b  10  83  dc! 70! 33  49! 7c! ca  6a  d8! 1a  5f! 92  0b! 00! e6   | !crc|           
  326225088 |  326245888 | Tag |81  2c! 69! 67  d8  43  af! 10  7c! 48! 4a  fc! 06! 39  82  2d! ef  be   | !crc|           
  326265648 |  326286448 | Tag |7e! b2! 6a  e8! fd! ab  01  e7! 78! e9  91! 5d  8b  db  87  b7  d3! 57!  | !crc|           
  326476688 |  326479056 | Tag |04  00                                                                   |     |           
  326667168 |  326669536 | Tag |04  00                                                                   |     |           
  326688160 |  326694048 | Tag |26  36  e5  58  ad                                                       |     |           
  326719776 |  326723296 | Tag |08  b6  dd                                                               |     |           
  326760976 |  326765712 | Tag |07  26  76  da                                                           |     |           
  326781712 |  326786384 | Tag |c4! 9a  0a! c7!                                                          |     |           
  326811152 |  326832016 | Tag |ba! 3c! 66! d0  4f  81! 4d! 8a  54  47  8f  a3! 09! c4  86  87! 73  40   | !crc|           
  326851728 |  326872592 | Tag |02! aa  15! 02  fb! 1a! 01  f3  4c  90! fa! 8e  c1! 1c  01! 05! 81  7a   | !crc|           
  326892416 |  326913216 | Tag |2d! 7d  3c! b0  cb! c4! fc! 82! ab! 6d  da  69  8e  be  05  34  1f  8d   | !crc|           
  370637168 |  370639536 | Tag |04  00                                                                   |     |           
  370827632 |  370830000 | Tag |04  00                                                                   |     |           
  370848608 |  370854496 | Tag |26  36  e5  58  ad                                                       |     |           
  373555200 |  373557568 | Tag |04  00                                                                   |     |           
  373745312 |  373747680 | Tag |04  00                                                                   |     |           
  373766432 |  373772320 | Tag |26  36  e5  58  ad                                                       |     |           
  376472640 |  376475008 | Tag |04  00                                                                   |     |           
  376663232 |  376665600 | Tag |04  00                                                                   |     |           
  376684224 |  376690112 | Tag |26  36  e5  58  ad                                                       |     |           
  587300736 |  587303104 | Tag |04  00                                                                   |     |           
  587483056 |  587485424 | Tag |04  00                                                                   |     |           
  587504160 |  587510048 | Tag |26  36  e5  58  ad                                                       |     |           
  587535776 |  587539296 | Tag |08  b6  dd                                                               |     |           
  590244336 |  590246704 | Tag |04  00                                                                   |     |           
  590265456 |  590271344 | Tag |26  36  e5  58  ad                                                       |     |           
  590297072 |  590300592 | Tag |08  b6  dd                                                               |     |           
  593005328 |  593007696 | Tag |04  00                                                                   |     |           
  593026448 |  593032336 | Tag |26  36  e5  58  ad                                                       |     |           
  593058064 |  593061584 | Tag |08  b6  dd                                                               |     |           
  595905440 |  595907808 | Tag |04  00                                                                   |     |           
  596095824 |  596098192 | Tag |04  00                                                                   |     |           
  596116800 |  596122688 | Tag |26  36  e5  58  ad                                                       |     |           
  596148544 |  596152064 | Tag |08  b6  dd                                                               |     |           
  596189760 |  596194432 | Tag |87  be  02  53                                                           |     |           
  596210496 |  596215168 | Tag |a1! 36  a7  7a!                                                          |     |           
  596239936 |  596260800 | Tag |1f  39! fa! bf! ad! 0e! 7f! b5  e3  a5  88  0a  0b! 14! 12! e5  89! f1   | !crc|           
  596280624 |  596301488 | Tag |86  e3! 6f  8c! 15! 27! 87  d5! 85  83! fd! c5  6d! a6! cf  85  a9! 6c!  | !crc|           
  596321328 |  596342128 | Tag |43  b2! 1a! e0  73! 31! 28! 0f  7d! 6b! 32! 15! a6! 1c  12  d7! f0  57!  | !crc|           
  596532288 |  596534656 | Tag |04  00                                                                   |     |           
  596722816 |  596725184 | Tag |04  00                                                                   |     |           
  596743792 |  596749680 | Tag |26  36  e5  58  ad                                                       |     |           
  596775536 |  596779056 | Tag |08  b6  dd                                                               |     |           
  596816752 |  596821488 | Tag |d8  fd  fb  a2                                                           |     |           
  596837488 |  596842224 | Tag |4e  60  15! 5d                                                           |     |           
  596866928 |  596887728 | Tag |a2! 2e  5d  18! 3f  76  e1! 0a  51! b0  88  42! e3! 9b  14  72! c1  d4   | !crc|           
  596907488 |  596928352 | Tag |42  cc  db  7e  86! 4a  2a! aa! 2f! b5! cb  ec  6a! d5  85  e6! fc  7e!  | !crc|           
  596948064 |  596968928 | Tag |e0  0b! d8  b1! c3  aa! f3! 28! 05  8d  15  65  f0! 41! 2c  a1  43! 00!  | !crc|           
  640074192 |  640076560 | Tag |04  00                                                                   |     |           
  640264624 |  640266992 | Tag |04  00                                                                   |     |           
  640285744 |  640291632 | Tag |26  36  e5  58  ad                                                       |     |           
  640317488 |  640321008 | Tag |08  b6  dd                                                               |     |           
  640358704 |  640363440 | Tag |4f  65  9f  ab                                                           |     |           
  640379440 |  640384112 | Tag |a8! e4! 84! 0c                                                           |     |           
  640408864 |  640429664 | Tag |a6! 1b! 58  55  75! 12! ae! 5b  b5! 74! df! 4e  b5! a0! f0  c0  ee! 6e!  | !crc|           
  640449440 |  640470240 | Tag |fd  59  33  96  79  7e! 4b! 40! cf! b9! 0f! 48  e7! 87! 95! 0c  92! 35   | !crc|           
  640490144 |  640510944 | Tag |ae! 19  6a  14! eb! 84  be! 53  ff! 99  ea  e8  10  2a  98! 0d  2a! b1   | !crc|           
  640697024 |  640699392 | Tag |04  00                                                                   |     |           
  640887472 |  640889840 | Tag |04  00                                                                   |     |           
  640908464 |  640914352 | Tag |26  36  e5  58  ad                                                       |     |           
  640940192 |  640943712 | Tag |08  b6  dd                                                               |     |           
  640981408 |  640986080 | Tag |37  91  d5  eb                                                           |     |           
  641002272 |  641006944 | Tag |43  e7  e8  0b!                                                          |     |           
  641031712 |  641052576 | Tag |69  60! 6a! 68! 3a  56  54! 31! b7! 51! cd! 6c  40  f0  ff! 15! 5c  3d   | !crc|           
  641072272 |  641093072 | Tag |56! a3! 4a  0d! 1c  a5! 6a! 29  8d! 9a  5d  cc! dc  01! 62! 77  e6  b7   | !crc|           
  641112976 |  641133776 | Tag |ec! 84! 03! 44! 71  80! 64! 53! 51! 71! a0  98  6b  6b  9c! 85! 6a! 17   | !crc|           
  641321056 |  641323424 | Tag |04  00                                                                   |     |           
  641342176 |  641348064 | Tag |26  36  e5  58  ad                                                       |     |           
  641373792 |  641377312 | Tag |08  b6  dd                                                               |     |           
  641415136 |  641419808 | Tag |be  1a  93  27                                                           |     |           
  641435872 |  641440544 | Tag |06! e7! 59! 9d!                                                          |     |           
  641465040 |  641465616 | Tag |0d                                                                       |     |           
  641548880 |  641549456 | Tag |08                                                                       |     |           
  641571920 |  641592720 | Tag |f8! 97  8a  85  a6! 40! 47! cb  62  d3! a9! 76  2d  ac  e5! a4  9c! 2b   | !crc|           
  641612480 |  641613056 | Tag |0a!                                                                      |     |           
  641696192 |  641696768 | Tag |0a!                                                                      |     |           
  641719344 |  641740208 | Tag |6e  39  bb! 57  bb! 6f  d9  b9! 98  8e! 2c  ca! 88  54  f9  7b  14  1c   | !crc|           
  641759792 |  641760368 | Tag |0d                                                                       |     |           
  641843616 |  641844192 | Tag |08                                                                       |     |           
  641866784 |  641887648 | Tag |12! cd  5b! 63! d9  2f  1d! 7e  06! 17  bf  0c  64! 0e! 09  6f! 60  37   | !crc|           
  696339472 |  696341840 | Tag |04  00                                                                   |     |           
  696529824 |  696532192 | Tag |04  00                                                                   |     |           
  696550816 |  696556704 | Tag |26  36  e5  58  ad                                                       |     |           
  696582560 |  696586080 | Tag |08  b6  dd                                                               |     |           
  696623632 |  696628368 | Tag |48  36  a1  54                                                           |     |           
  696644496 |  696649168 | Tag |7b  59! c7! 06                                                           |     |           
  696673936 |  696694736 | Tag |37! fe  ba! 92  ec! b4! 90  b7  be  a0! 1d! e1! dc! 42! ea! 46! e4  7b   | !crc|           
  696714512 |  696735312 | Tag |75! b2! 76! bc! a3  67! ca  fd! 99! dd! 98! db  67  59! a7! 95  a8  0e!  | !crc|           
  696755328 |  696776192 | Tag |63! 0c! 22! c3! 0d  64  9f! 97  74  14  18! a6! 55! 7a! a9! 6c  3b! d1!  | !crc|           
  696962080 |  696964448 | Tag |04  00                                                                   |     |           
  697152624 |  697154992 | Tag |04  00                                                                   |     |           
  697173616 |  697179504 | Tag |26  36  e5  58  ad                                                       |     |           
  697205344 |  697208864 | Tag |08  b6  dd                                                               |     |           
  697246560 |  697251232 | Tag |7d  3c  0e  05                                                           |     |           
  697267296 |  697272032 | Tag |ba  9d! 3e  89                                                           |     |           
  697296736 |  697317536 | Tag |f5! 5a! f6! 2f! 51! ff! c0! 01  fa  12! de  6b  67! d0! c1  6b! 41! 1b   | !crc|           
  697337296 |  697358096 | Tag |dc  23! e3! ba  b5! ce  d8  18  9c! d2  1f! 05  87! 63! 25! cf! b5! ec!  | !crc|           
  697378000 |  697398800 | Tag |bd! 15! 04  ac! 41  00  f2! 47  10! 54  84  dd! 75  55! da! 21  5f! 72   | !crc|           
  697586208 |  697588576 | Tag |04  00                                                                   |     |           
  697607200 |  697613088 | Tag |26  36  e5  58  ad                                                       |     |           
  697638944 |  697642464 | Tag |08  b6  dd                                                               |     |           
  697680144 |  697684816 | Tag |75  49  4d  d8                                                           |     |           
  697700880 |  697705552 | Tag |28! 70  35! a9                                                           |     |           
  697730192 |  697730832 | Tag |03!                                                                      |     |           
  697813888 |  697814528 | Tag |02                                                                       |     |           
  697837056 |  697857856 | Tag |1e  8c  3c! 76  69  36  d6  28  ad! c0! 98! 72  2c  d8! b8  7a  21  0f   | !crc|           
  697877504 |  697878144 | Tag |04                                                                       |     |           
  697961328 |  697961968 | Tag |07                                                                       |     |           
  697984496 |  698005360 | Tag |2e  b4  45! 16  b1! e5! 43  6d  fd  ba  22  ff  b1! 8f  77! e2! 71  88!  | !crc|           
  698025072 |  698025648 | Tag |08                                                                       |     |           
  698108768 |  698109344 | Tag |0b                                                                       |     |           
  698131936 |  698152800 | Tag |32  ed! 41  35! 9b! 9e  99! 22  52  84! 2e! 25  b7! f9  65! 43  f7! 7c   | !crc|           
  776746480 |  776748848 | Tag |04  00                                                                   |     |           
  776928800 |  776931168 | Tag |04  00                                                                   |     |           
  776949904 |  776955792 | Tag |26  36  e5  58  ad                                                       |     |           
  776981520 |  776985040 | Tag |08  b6  dd                                                               |     |           
  779690064 |  779692432 | Tag |04  00                                                                   |     |           
  779711056 |  779716944 | Tag |26  36  e5  58  ad                                                       |     |           
  779742800 |  779746320 | Tag |08  b6  dd                                                               |     |           
  891206576 |  891208944 | Tag |04  00                                                                   |     |           
  891388512 |  891390880 | Tag |04  00                                                                   |     |           
  891409632 |  891415520 | Tag |26  36  e5  58  ad                                                       |     |           
  891441232 |  891444752 | Tag |08  b6  dd                                                               |     |           
  894149424 |  894151792 | Tag |04  00                                                                   |     |           
  894170544 |  894176432 | Tag |26  36  e5  58  ad                                                       |     |           
  894202160 |  894205680 | Tag |08  b6  dd                                                               |     |           
  896920512 |  896922880 | Tag |04  00                                                                   |     |           
  896941632 |  896947520 | Tag |26  36  e5  58  ad                                                       |     |           
  896973232 |  896976752 | Tag |08  b6  dd                                                               |     |           
  899820384 |  899822752 | Tag |04  00                                                                   |     |           
  900010816 |  900013184 | Tag |04  00                                                                   |     |           
  900031792 |  900037680 | Tag |26  36  e5  58  ad                                                       |     |           
  900063536 |  900067056 | Tag |08  b6  dd                                                               |     |           
  900104752 |  900109488 | Tag |39  2a  a1  4c                                                           |     |           
  900125488 |  900130224 | Tag |69! a5! 60  df                                                           |     |           
  900155056 |  900175856 | Tag |27  36  67  9b! 7f  21  49! 8d! bb! 55  f6  48  7f! 98  b6  25! c2  f0   | !crc|           
  900195616 |  900216480 | Tag |0d! ac! fc  76  30! 74! 2b  d3  60  c0  c7! e5! 5b  35  68! 69! 8b  8b!  | !crc|           
  900236192 |  900254560 | Tag |85! a7  c6  14  c6  71! a5  7c! 5d  19  a5! ad  1f  7f  cd  fe           | !crc|           
  900447232 |  900448512 | Tag |04                                                                       |     |           
  900659280 |  900659472 | Tag |01                                                                       |     |           
  900862960 |  900868144 | Tag |c1! ce! b0! 89! 08                                                       |     |           
  937164240 |  937166608 | Tag |04  00                                                                   |     |           
  937354656 |  937357024 | Tag |04  00                                                                   |     |           
  937375648 |  937381536 | Tag |26  36  e5  58  ad                                                       |     |           
  937407376 |  937410896 | Tag |08  b6  dd                                                               |     |           
  937448720 |  937453392 | Tag |a0  15  d1  fa                                                           |     |           
  937469456 |  937474128 | Tag |a5! 43  9f! 83!                                                          |     |           
  937498896 |  937519760 | Tag |dd  fe! 5b! ba! b7! 25  6c! b0  e5  cb  fb! 9a! 4c! b4  db! 31! 04! 71!  | !crc|           
  937539584 |  937560448 | Tag |d5  93! b6! d2  4d  25  ff! 72  df  9b! 89! e5! 57  a9  9a! 68  67  7a   | !crc|           
  937580288 |  937601152 | Tag |cc! f4! a1  a9  7a! 2b  44  5e! 99! e1! 0d  fa! bf  fa! c8! c1  ea! 9b   | !crc|           
  937787200 |  937789568 | Tag |04  00                                                                   |     |           
  937977696 |  937980064 | Tag |04  00                                                                   |     |           
  937998672 |  938004560 | Tag |26  36  e5  58  ad                                                       |     |           
  938030288 |  938033808 | Tag |08  b6  dd                                                               |     |           
  938071504 |  938076240 | Tag |b9  5f  5d  49                                                           |     |           
  938092240 |  938096912 | Tag |1a! e0! 87! 57!                                                          |     |           
  938121680 |  938142544 | Tag |8d  22  4d  bb! d7  1c! 34! 81  cf! 8d  79! 08  b1  6b! 81  7c! ae! 25   | !crc|           
  938162368 |  938183168 | Tag |db  ca! 90  f8  63! 1f! dd  aa! cd  0e  42  8f  cc! 65! bb  f1  bf  6d!  | !crc|           
  938203072 |  938223936 | Tag |93! 3b  d1! cc  06! 41  60! 18  42  4b  1d  b0  d3! d2  0f  72! a1! 9c!  | !crc|           
  938411168 |  938413536 | Tag |04  00                                                                   |     |           
  938432288 |  938438176 | Tag |26  36  e5  58  ad                                                       |     |           
  938464016 |  938467536 | Tag |08  b6  dd                                                               |     |           
  938505232 |  938509968 | Tag |11  38  d7  a8                                                           |     |           
  938525968 |  938530704 | Tag |d7  61! 79  34                                                           |     |           
  938555152 |  938555728 | Tag |09!                                                                      |     |           
  938638976 |  938639552 | Tag |08                                                                       |     |           
  938662016 |  938682880 | Tag |c4! b3! 33! 8d  41! 81! 26! d7  1d! eb! ce  fc! 69  ce  5c! 71  eb! 9f!  | !crc|           
  938702592 |  938703232 | Tag |02                                                                       |     |           
  938786288 |  938786928 | Tag |04                                                                       |     |           
  938809456 |  938830320 | Tag |40  a1  0a  0a  8e! 51  18  da  67  3a! 0a! dc! 23  8d! f5  51  41  92   | !crc|           
  938850016 |  938850656 | Tag |03!                                                                      |     |           
  938933856 |  938934496 | Tag |02                                                                       |     |           
  938956896 |  938977760 | Tag |19  25  55  2b! 53! c7  5d! 91  fd! b4  83! 0b  9b! 24! 52! ef  0e  c9!  | !crc|           
 1060259968 | 1060262336 | Tag |04  00                                                                   |     |           
 1060450432 | 1060452800 | Tag |04  00                                                                   |     |           
 1060471552 | 1060477440 | Tag |26  36  e5  58  ad                                                       |     |           
 1060503168 | 1060506688 | Tag |08  b6  dd                                                               |     |           
 1063211552 | 1063213920 | Tag |04  00                                                                   |     |           
 1063232544 | 1063238432 | Tag |26  36  e5  58  ad                                                       |     |           
 1063264288 | 1063267808 | Tag |08  b6  dd                                                               |     |           
 1090291280 | 1090293648 | Tag |04  00                                                                   |     |           
 1090481760 | 1090484128 | Tag |04  00                                                                   |     |           
 1090502736 | 1090508624 | Tag |26  36  e5  58  ad                                                       |     |           
 1090534480 | 1090538000 | Tag |08  b6  dd                                                               |     |           
 1090575696 | 1090580368 | Tag |24  16  d8  d1                                                           |     |           
 1090596432 | 1090601104 | Tag |61! b0  58  8b                                                           |     |           
 1090625856 | 1090646720 | Tag |62  a5  4f! 12! 24  a4  a2! 61! 60  70! e6! 0e  1e! cf! ca  14! 77  ff!  | !crc|           
 1090666432 | 1090687232 | Tag |21  f6  ab  ed! c4  da  31! ff  b3  cd! 9d! d9  ac! c3  ac! 18! e5! f5   | !crc|           
 1090717760 | 1090738560 | Tag |7c  d0! 41  9e! e0! ed! ab! 62! 4f  d1  2c  64! a4  36  1d  eb  9d! f1!  | !crc|           
 1090928800 | 1090931168 | Tag |04  00                                                                   |     |           
 1091119248 | 1091121616 | Tag |04  00                                                                   |     |           
 1091140224 | 1091146112 | Tag |26  36  e5  58  ad                                                       |     |           
 1091171984 | 1091175504 | Tag |08  b6  dd                                                               |     |           
 1091213056 | 1091217792 | Tag |dc  96  06  d5                                                           |     |           
 1091233920 | 1091238592 | Tag |97  1b! d4  f5                                                           |     |           
 1091263232 | 1091284032 | Tag |a1! 5d  4e! b9  1a  71  39  dd! d8! dd! 02  66  9c! 01! 47! 91  2e  24   | !crc|           
 1091303920 | 1091324720 | Tag |e9  9d  8e  7a  9f! b7  a1! 96  b6! ab  52! 35  df  05! c3  b1! d5  07!  | !crc|           
 1091344496 | 1091365296 | Tag |4e! 71! 4b! 0a! 07! 92! f8  1a  6f! 11! f6! cc! 21! cf  e3  52  56  b2   | !crc|           
 1091560640 | 1091563008 | Tag |04  00                                                                   |     |           
 1091581632 | 1091587520 | Tag |26  36  e5  58  ad                                                       |     |           
 1091613376 | 1091616896 | Tag |08  b6  dd                                                               |     |           
 1091654592 | 1091659264 | Tag |d3  fb  83  65                                                           |     |           
 1091675312 | 1091679984 | Tag |fc  8b  ec  59                                                           |     |           
 1091704496 | 1091705072 | Tag |0e                                                                       |     |           
 1091788336 | 1091788912 | Tag |08                                                                       |     |           
 1091811488 | 1091832352 | Tag |81! d1  7f  94  13  51! 2e! 8c! 57! a6  e5  99! 0d! d9  28  84! 15  a2   | !crc|           
 1091851936 | 1091852576 | Tag |06!                                                                      |     |           
 1091935632 | 1091936272 | Tag |04                                                                       |     |           
 1091958816 | 1091979680 | Tag |78! c9! 4a! 52  fd! 10! a3  f6! 4b  0d  ca! ba  2c! 7c  bf! a1! bc! fe   | !crc|           
 1091999248 | 1091999824 | Tag |08                                                                       |     |           
 1092083072 | 1092083648 | Tag |0a!                                                                      |     |           
 1092106112 | 1092126912 | Tag |3f! c9  66! a6! 21  fe! 18! 76  45! 2d  41  5e! 38! 30! a8! 66! e3! 64!  | !crc|

**Comment by iceman1001** [comment]
If you would compare with latest offical source and iceman fork, you would find that they would print the same output style when issue the  "hf 14a list"     If your client outputs that format,  congrats you are running on a at least 6 year old version of the software.  

I think you are trying to run mfkey64 and have no idea which parameters to put into it.   I suggest you read the helptext and the textfiles inside that folder.  Also search on pm3 forum for more details.
