### ISSUE TITLE
mkversion.pl - env: unknown option -- S

### ISSUE THREAD

**Issue by Gator96100** [iceman1001/proxmark3#264]
While validating ProxSpace I noticed this error when mkversion.pl is called:
```
env: unknown option -- S
Try 'env --help' for more information.
```
Same happened on Ubuntu.
Should it just be `env which git`?

**Comment by iceman1001** [comment]
@cjbrigato  feel free to answer this one.

**Comment by iceman1001** [comment]
@hsanjuan   the **env -S**  in mkversion.pl     
I also get faults on my ubuntu setup.

**Comment by iceman1001** [comment]
@Gator96100   I removed the -S   it should work better now.
