### ISSUE TITLE
loclass fails

### ISSUE THREAD

**Issue by ralik** [iceman1001/proxmark3#266]
loclass fails all the time (for several readers).
however, 'sim 2' works and 'iclass list' looks good.
Tested on latest update.

**Comment by iceman1001** [comment]
Are you sure the readers used is configured for elite mode?

**Comment by ralik** [comment]
Yes, I have both legacy and SE standard credentials and they are not read by the readers.

**Comment by ralik** [comment]
Could it be that it is filtering blacklisted CSNs? Anyway to confirm that?

**Comment by iceman1001** [comment]
I heard the HID readers has a numerous ways of making sure the sim2 attack fails.   Blacklisting would be one.  Hence I say test with official and iceman repo, since they are different. 

So your problems is that the iclass sim2 on iceman works,  but the loclass doesnt?

**Comment by ralik** [comment]
On a official, it just gives the "unknown command received from reader" error.

On iceman:
sim 2 works (see https://pastebin.com/z7rrcye3)
loclass doesn't (see https://pastebin.com/W4JyN6BS)

**Comment by iceman1001** [comment]
closed because of inactivity
