### ISSUE TITLE
Gentoo install

### ISSUE THREAD

**Issue by vyrus001** [iceman1001/proxmark3#267]
Had issues installing on Gentoo => 4.9.24-hardened #6 SMP

got errs saying the following:
`make[3]: Entering directory '/proxmark3/liblua'
gcc -o lua   lua.o liblua.a -lm -Wl,-E -ldl -lreadline -ltermcap -lncurses 
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -ltermcap`

resolved the issue by first installing the legacy compatibility package
`sudo emerge --ask sys-libs/libtermcap-compat`

then adding a symlink so ld could find it
`sudo ln -s /usr/lib64/libtermcap.so.2.0.8 /usr/lib64/libtermcap.so`

Adding this here incise anybody else has this issue or seeks to fix the problem within the make file permanently.

**Comment by RfidResearchGroup** [comment]
Nice!

How about you update the wiki on official proxmark guthub for the Gentoo entry?  You find it here: 
https://github.com/Proxmark/proxmark3/wiki/Gentoo-Linux
