### ISSUE TITLE
hf mf chk doesn't work

### ISSUE THREAD

**Issue by microsoftmice** [iceman1001/proxmark3#273]
Hi iceman. I flashed the newest version.
when I useing the command hf mf chk *1 ? d. It can't get the right keys(all sectors useing the FFFFFFFFFFFF except sector 10)
all of the keys are not founded. Can you check it?

Btw If useing the hf mf chk * a/b ? d , it works. the offical version works.

**Comment by iceman1001** [comment]
Which device are you using?

the thing is that this repo is behind in fixes,  most recent source is in the RRG repo.   if you don't have a rdv4 you can still compile it to work with non rdv4 devices.

**Comment by iceman1001** [comment]
any news?

**Comment by iceman1001** [comment]
closed because of inactivity
