### ISSUE TITLE
Ultralight/NTAG simulation sends incorrect ACK/NAK answer

### ISSUE THREAD

**Issue by McEloff** [iceman1001/proxmark3#282]
Method SimulateIso14443aTag(...) sends incorrect ACK/NAK answer for commands:
- MIFARE_ULEV1_READ_CNT
- MIFARE_ULEV1_INCR_CNT
- MIFARE_ULEV1_CHECKTEAR
It is used EmSendCmd(...) function call, but must use EmSend4bit(...). Datasheets (NTAG213_215_216.pdf, MF0ULX1.pdf) defines ACK/NAK as 4-bits commands

**Comment by iceman1001** [comment]
this repo is lagging behind,  however if you are interesting in the latest stuff head over to https://github.com/RfidResearchGroup/proxmark3   it can easily be compiled for non rdv4 device. 

In there I added the suggested 4bit responses
