### ISSUE TITLE
hf mf csetuid atqa sak issue

### ISSUE THREAD

**Issue by bitf1ipper** [iceman1001/proxmark3#283]
Not sure if the root cause of this issue is related to the Proxmark3 or the Chinese magic card.  Using magic card gen 1a no matter what I do I cannot set the SAK properly.  It always returns SAK 8.
pm3 --> hf mf csetuid cfb89c9f 0f01 01
--wipe card:NO  uid:CF B8 9C 9F
old block 0:  CF B8 9C 9F 74 FF 01 0F C4 29 00 00 00 00 00 13
new block 0:  CF B8 9C 9F 74 01 01 0F C4 29 00 00 00 00 00 13
old UID:00 00 00 00
new UID:CF B8 9C 9F
pm3 --> hf 14a reader
 UID : CF B8 9C 9F
ATQA : 0f 01
 SAK : 08 [2]
TYPE : NXP MIFARE CLASSIC 1k | Plus 2k SL1 | 1k Ev1
proprietary non iso14443-4 card found, RATS not supported
Answers to magic commands (GEN 1a): YES
Prng detection: WEAK

The puzzling thing is if I run hf mf cgetblk 0 it returns:
pm3 --> hf mf cgetblk 0
--block number: 0
data: CF B8 9C 9F 74 01 01 0F C4 29 00 00 00 00 00 13
I can see that offset 0x05 is 01 but I suspect it should be 81.  I also tried "hf mf csetuid cfb89c9f 0f01 81" which does set it to 81 but of course that still returns SAK 08.  So I'm wondering if this is a bug on the pm3's part or if it is the magic card gen 1a?

**Comment by iceman1001** [comment]
That would be one of those odd magic cards.  You can set atqa / uid on it but not sak.
