### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by 0xface-dev** [iceman1001/proxmark3#287]
![bug1](https://user-images.githubusercontent.com/3508145/57195780-167cef80-6f89-11e9-9cb5-6b3ba9d027a4.png)
![bug2](https://user-images.githubusercontent.com/3508145/57195782-1977e000-6f89-11e9-8cff-c8ff5f4f8f07.png)

no display key
===========================================================
but use https://github.com/proxmark3/ 
display key

![1](https://user-images.githubusercontent.com/3508145/57195826-83908500-6f89-11e9-8a40-131fc3f30201.png)

**Comment by iceman1001** [comment]
depends.
looks like you have mixed firmware & client from  iceman repo vis official repo.  
The general recommendation is never to mix firmware & client from different builds, repos.  Always use the same client as you used when you flashed.

**Comment by 9844201** [comment]
![QQ截图20190505232306](https://user-images.githubusercontent.com/3508145/57196173-cb64db80-6f8c-11e9-8c81-ebd8a3b9018a.png)
The firmware and client are the same

**Comment by 0xface-dev** [comment]
![QQ截图20190505232428](https://user-images.githubusercontent.com/3508145/57196189-f7805c80-6f8c-11e9-81d7-58600cfa9ec4.png)
Firmware and client are the same version

**Comment by iceman1001** [comment]
if you look at the found keys in your run with official repo,   00270088bf51 it isn't in the default keys used in your iceman run.   The res column indicates success (1)/ failure (0)

The bug would be why official repo finds a key not used in the dictionary.
