### ISSUE TITLE
Need help buying this product

### ISSUE THREAD

**Issue by cefedrific** [iceman1001/proxmark3#289]
hello and very great job!!

Here I intend to buy this jewelry but I would like to know if I can crack the chip cards for coffee lyovel with this product::

New proxmark3 develop suit Kits 3.0 proxmark RDV4 NFC RFID reader writer for rfid nfc card copier clone crack 2 USB port 512K
sur aliexppress

because I saw also this product which has a plug or adapter that we put on the chip directly so I think it will be for lyovel

Created by
ProxGrind's Proxmark3 Rdv 4.0
sur le site kickstarter

and with the first product is that it is possible because I have not seen any plug or adapter must he buy it apart? I am confused can you m help me for my purchase thank you in advance..

**Comment by iceman1001** [comment]
These are the offical distributors of Proxmark3 RDV4.  

https://sneaktechnology.com/product/001/
https://lab401.com/collections/rfid-tools/products/proxmark-3-rdv4
https://hackerwarehouse.com/product/proxmark3-rdv4-kit/
