### ISSUE TITLE
Compilation problem [-Werror=address-of-packed-member]

### ISSUE THREAD

**Issue by nemanjan00** [iceman1001/proxmark3#294]
```
arm-none-eabi-gcc -c -I../include -I../common -I. -Wall -Werror -pedantic -Wunused -std=c99 -DWITH_CRC -DON_DEVICE -DWITH_LF -DWITH_HITAG -DWITH_ISO15693 -DWITH_LEGICRF -DWITH_ISO14443b -DWITH_ISO14443a -DWITH_ICLASS -DWITH_FELICA -DWITH_FLASH -DWITH_SMARTCARD -DWITH_HFSNOOP -DWITH_LF_SAMYRUN -fno-strict-aliasing -ffunction-sections -fdata-sections -DZ_SOLO -DZ_PREFIX -DNO_GZIP -DZLIB_PM3_TUNED -I../zlib -I. -Os -mthumb -mthumb-interwork -o obj/appmain.o appmain.c 
appmain.c: In function 'UsbPacketReceived':
appmain.c:622:40: error: taking address of packed member of 'struct <anonymous>' may result in an unaligned pointer value [-Werror=address-of-packed-member]
  622 |    setSamplingConfig((sample_config *) c->d.asBytes);
      |                                        ^
cc1: all warnings being treated as errors
make[1]: *** [../common/Makefile.common:77: obj/appmain.o] Error 1
make[1]: Leaving directory '/home/nemanjan00/gitProgs/proxmark3/armsrc'
make: *** [Makefile:35: armsrc/all] Error 2
```

Temporary solution is removing -Werror from common/Makefile.common... I am not C/C++ guy, so, was not able to solve real problem. 

Building on Arch, gcc version: arm-none-eabi-gcc 9.1.0-1

**Comment by iceman1001** [comment]
@doegox  This one is for you,  Arch linux...     I suppose this exists in RRG repo aswell. 
Unaligned pointer access.

**Comment by iceman1001** [comment]
@nemanjan00  you wouldn't mind testing  https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Installation_Instructions/Linux-Installation-Instructions.md   and compiling the RRG repo?

**Comment by nemanjan00** [comment]
Compiles no problems

BTW, thanks for fast response, and also, for this dork and work in community

**Comment by doegox** [comment]
Yes I tested rrg on Arch docker, compiles fine

**Comment by iceman1001** [comment]
sounds like I can close this one.

**Comment by nemanjan00** [comment]
RRG does compile, but, this one does not

**Comment by iceman1001** [comment]
use RRG,  adjust Makefile.platform file to compile for your proxmark3 device

**Comment by nemanjan00** [comment]
Ok, thanks!
