### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by xakod** [iceman1001/proxmark3#296]
`arm-none-eabi-gcc -c -I../include -I../common -I. -Wall -Werror -pedantic -Wunused -std=c99 -DWITH_CRC -DON_DEVICE -DWITH_LF -DWITH_HITAG -DWITH_ISO15693 -DWITH_LEGICRF -DWITH_ISO14443b -DWITH_ISO14443a -DWITH_ICLASS -DWITH_FELICA -DWITH_FLASH -DWITH_SMARTCARD -DWITH_HFSNOOP -DWITH_LF_SAMYRUN -fno-strict-aliasing -ffunction-sections -fdata-sections -DZ_SOLO -DZ_PREFIX -DNO_GZIP -DZLIB_PM3_TUNED -I../zlib -I. -Os -mthumb -mthumb-interwork -o obj/appmain.o appmain.c 
appmain.c: In function 'UsbPacketReceived':
appmain.c:622:40: error: taking address of packed member of 'struct <anonymous>' may result in an unaligned pointer value [-Werror=address-of-packed-member]
  622 |    setSamplingConfig((sample_config *) c->d.asBytes);
      |                                        ^
cc1: all warnings being treated as errors
make[1]: *** [../common/Makefile.common:77: obj/appmain.o] Error 1
make[1]: Leaving directory '/home/net_client/prox/proxmark3/armsrc'
make: *** [Makefile:35: armsrc/all] Error 2
`

Arch linux with gcc 9.1.0

**Comment by iceman1001** [comment]
I suggest you try out  https://github.com/RfidResearchGroup/proxmark3  repo instead.
You can easily compile it for all proxmark3 devices.
Look into compiling documentation
