### ISSUE TITLE
Unable to correctly interact with some EM-Marin tags

### ISSUE THREAD

**Issue by S1yk3r** [iceman1001/proxmark3#297]
I met a EM-Marin TAG ID which is impossible to read/write on iceman PM3 firmware, example: **24001AC532**. Maybe its value violates some standard range rules, but i met it on are real intercom, and official PM3 firmware works well with it.
(I use precompiled PM3 iceman bulids from here: https://drive.google.com/open?id=1mMgdfnSEgFvA77xvbG_VnaLrZJHnvcSP/)

**Comment by iceman1001** [comment]
This repo has been deprecrated,  I suggest you swap over to RRG/Iceman repo for the latest changes.
ref
https://github.com/RfidResearchGroup/proxmark3
