### ISSUE TITLE
hf legic sim - not working

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/proxmark3#38]
Simulation for legic is not working at the moment.

The following outline on how it should work as below:
- hf legic reader
- hf legic dump
- hf legic eload 
- hf legic sim
- hf legic esave

**Comment by ikarus23** [comment]
bump :)

**Comment by iceman1001** [comment]
its a hard one to solve for me,  since I dont have a valid reader to compare and debug with.

**Comment by iceman1001** [comment]
@dandreas is working on a  I/Q based solution which will increase reading/writing/simulation for Legic Prime very much.   **exciting!**

**Comment by iceman1001** [comment]
Update
@dandreas has legic sim working,   Any day now he will push it!

**Comment by ikarus23** [comment]
I just saw it in the upstream of the official proxmark repo. Really great work. I will test as soon as I get my hands on a Legic Prime reader.
