### ISSUE TITLE
valgrind / gdb  cmdhfmfhard.c

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/proxmark3#48]
With @matrix  latest changes, I started to get some crashes.  Thanks for the tip on using valgrind.
Out of the box it doesn't work because the pm3 client is compiled with -o3.  Change that to -o1 and you can use valgrind better.    Hook it up with GDB,  and when running the 'hf mf hardnested' command it now breaks as seen below.  My first guess is that the comment made by @piwi,  
"// use logarithms to avoid overflow with huge factorials (double type can only hold 170!)"

```
Program received signal SIGILL, Illegal instruction.
[Switching to Thread 5740]
p_hypergeometric (N=N@entry=256, K=K@entry=32, n=n@entry=4, k=k@entry=0) at cmdhfmfhard.c:264
264         return exp(log_result);
(gdb) 
```

**Comment by iceman1001** [comment]
```
#0  p_hypergeometric (N=N@entry=256, K=K@entry=32, n=n@entry=10, k=k@entry=0) at cmdhfmfhard.c:264
#1  0x0808260b in p_hypergeometric (N=N@entry=256, K=K@entry=32, n=n@entry=10, k=k@entry=1) at cmdhfmfhard.c:276
#2  0x0808260b in p_hypergeometric (N=N@entry=256, K=K@entry=32, n=n@entry=10, k=k@entry=2) at cmdhfmfhard.c:276
#3  0x0808260b in p_hypergeometric (N=N@entry=256, K=K@entry=32, n=n@entry=10, k=k@entry=3) at cmdhfmfhard.c:276
#4  0x0808260b in p_hypergeometric (N=N@entry=256, K=<optimized out>, n=n@entry=10, k=k@entry=4) at cmdhfmfhard.c:276
#5  0x080826ec in sum_probability (k=4, n=10, K=32) at cmdhfmfhard.c:287
#6  estimate_second_byte_sum () at cmdhfmfhard.c:577
#7  0x08082e3a in acquire_nonces (blockNo=blockNo@entry=0 '\000', keyType=keyType@entry=0 '\000', 
    key=key@entry=0x6291af0 <incomplete sequence \374>, trgBlockNo=trgBlockNo@entry=36 '$', 
    trgKeyType=trgKeyType@entry=0 '\000', nonce_file_write=nonce_file_write@entry=false, slow=slow@entry=false)
    at cmdhfmfhard.c:843
#8  0x0808587a in mfnestedhard (blockNo=blockNo@entry=0 '\000', keyType=keyType@entry=0 '\000', 
    key=key@entry=0x6291af0 <incomplete sequence \374>, trgBlockNo=trgBlockNo@entry=36 '$', 
    trgKeyType=trgKeyType@entry=0 '\000', trgkey=trgkey@entry=0x0, nonce_file_read=false, 
    nonce_file_write=nonce_file_write@entry=false, slow=slow@entry=false, tests=tests@entry=0) at cmdhfmfhard.c:1817
#9  0x08078dba in CmdHF14AMfNestedHard (Cmd=<optimized out>) at cmdhfmf.c:1062
#10 0x08090b08 in CmdsParse (Commands=Commands@entry=0x81134e0 <CommandTable>, Cmd=<optimized out>, 
    Cmd@entry=0xbef1166 "hardnest 0 a fc00018778f7 36 a") at cmdparser.c:69
#11 0x0807c100 in CmdHFMF (Cmd=0xbef1166 "hardnest 0 a fc00018778f7 36 a") at cmdhfmf.c:2510
#12 0x08090b08 in CmdsParse (Commands=Commands@entry=0x8112f80 <CommandTable>, Cmd=<optimized out>, 
    Cmd@entry=0xbef1163 "mf hardnest 0 a fc00018778f7 36 a") at cmdparser.c:69
#13 0x08068cee in CmdHF (Cmd=0xbef1163 "mf hardnest 0 a fc00018778f7 36 a") at cmdhf.c:945
#14 0x08090b08 in CmdsParse (Commands=Commands@entry=0x8113fc0 <CommandTable>, Cmd=<optimized out>, 
    Cmd@entry=0xbef1160 "hf mf hardnest 0 a fc00018778f7 36 a") at cmdparser.c:69
```

**Comment by iceman1001** [comment]
http://pastebin.com/UCKYUUxJ

**Comment by iceman1001** [comment]
Almost forgot the varible value.  Seems like a negative float and exp doesnt like eachother

`log_result = -1,3611116341317357`

**Comment by matrix** [comment]
https://github.com/iceman1001/proxmark3/blob/master/client/cmdhfmfhard.c#L910-L911

Retry using the commented original values

**Comment by iceman1001** [comment]
Well, I don't know if this nonces.bin file is wrong pre se, but it caused a seg kill when it was made.
https://www.sendspace.com/file/jrgi9u

**Comment by osysltd** [comment]
seems hardnested is broken currently btw, doesn't work, very strange behavior (number of bytes going down) and always the same rollback byte (no matter what sectors\key types)

--target block no: 63, target key type:A, known target key: 0x000000000000 (not set), file action: 
none, Slow: Yes, Tests: 0  
Allocating memory for partial statelists...
Generating partial statelists...
Generating bitflip statelist...
Acquiring nonces...
Checking for Filter Flip Properties...
Acquired  1568 nonces ( 1548 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 13
Acquired  2016 nonces ( 1978 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 9
Acquired  2576 nonces ( 2514 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 1
Acquired  3024 nonces ( 2942 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 0
Acquired  3584 nonces ( 3468 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 0
Acquired  4032 nonces ( 3890 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 0
Generating crypto1 state candidates... 
Number of possible keys with Sum(a0) = 128: 117726714265600 (2^46.7)
Number of remaining possible keys: 482916425164 (2^38.8)
Time for generating key candidates list: 5 seconds  
Brute force phase starting.  
Using 128-bit bitslices  
Bitslicing best_first_byte^uid[3](rollback byte): 5D ...  
Bitslicing nonces...  
Starting 2 cracking threads to search 34 buckets containing a total of 482916425164 states...

**Comment by iceman1001** [comment]
Yeah, I noticed the counting down of guessed sum(a8) ,  funny.
Did it find the key?

**Comment by osysltd** [comment]
Nope, hf mf hard is broken currently.

**Comment by iceman1001** [comment]
Partly broken,  since I and @matrix  can get it to solve keys.
but I agree not stable at all.

**Comment by osysltd** [comment]
I've tried for two days against two sectors using different combination of known sectors\keys with no luck ;(

**Comment by iceman1001** [comment]
if you add "w" to your command,  and share the collected nonce file,  that might help out while debugging.

**Comment by iceman1001** [comment]
Looking at generating_candidates call,  it eventually ends up in the p_hypergeometric function.
With some comments from piwi, and the sigill comes..  @aczid thought it could be a memalignment problem.  Some mallac not correct?

**Comment by osysltd** [comment]
I've uploaded nonces and log here:  https://www.idrive.com/idrive/sh/sh?k=d7k8x1v3g6

**Comment by osysltd** [comment]
d209443322a410eadd9746ac74c6a8b4899788a9 works great with the same conditions

**Comment by osysltd** [comment]
Per my tests the best outcome is from f6c56cd204e1548b3cf4404b44f44fb3e13b45d9 revision.

**Comment by matrix** [comment]
Hi @Osys,
what's about your tests?
I see in your log an unknown bootrom name/version, different that os
version.
Also your proxmark hardware seems old revision, all correct?

**Comment by osysltd** [comment]
Hi Matrix, 
bootrom never flashed, stock one (from china). HW version is Easy. Os version is dirty due to change in common/Makefile (comment out APP_CFLAGS HAS_512_FLASH).
No more changes though...

Currently os image from last revision however client side is from this commit f6c56cd204e1548b3cf4404b44f44fb3e13b45d9

**Comment by matrix** [comment]
I'm not Iceman and I think you need flash also the bootrom before do other
"test" :)

Thanks,
matrix

**Comment by osysltd** [comment]
Already corrected, sorry ;)
Bootrom have nothing to do with OS image, it is there only to actually flash OS image. 
As an outcome of some discussions with @iceman1001, Easy is like an old hardware version (green one), yes.

**Comment by matrix** [comment]
I test the original hardnested attack also in old proxmark hardware and I
see a lot of errors like segfault, wrong 13bytes keys, unable to found
correct keys, etc.
With revision 2 of proxmark the attack work better (tested on linux and
osx).

**Comment by osysltd** [comment]
Do you have an idea how to get it working no matter what hardware?

**Comment by iceman1001** [comment]
To be honest, I've lots of problems with "older green" pm3 running "hf mf mifare" or "hf mf hardnested".
its like older pm3 is too slow.  The RDV1 or RDV2 works fine besides this mem corruption.
I'm gonna look into changing the p_hypergeometric function.

**Comment by matrix** [comment]
Old hw produce unstable results.
I think it's better answer that in proxmark forum

**Comment by osysltd** [comment]
Or revert changes to f6c56cd204e1548b3cf4404b44f44fb3e13b45d9 ;) As it seems the most working solution right now.

**Comment by matrix** [comment]
Or fork iceman repository and do what you want without ask to nobody ?
There're infinite solutions around you :)

**Comment by osysltd** [comment]
I'm not so well coder (but Im trying to learn :) therefore only I can help with is provide feedback. And the feedback as follows - currently hf mf hard doesn't work well as it used to...

**Comment by matrix** [comment]
I'm only a coder, I can only write code ... :)

**Comment by osysltd** [comment]
Then do please optimize the code :)

**Comment by matrix** [comment]
Hi @iceman1001 
I tried your nonces.bin but it is corrupt ...

**Comment by osysltd** [comment]
Btw @matrix, my github name is not @osys but @osysltd :)

**Comment by iceman1001** [comment]
How about you two stop the passive agressive posts?   So fine,  @osysltd  use the older commits that works for you and you will be happy.
If you provide with more details than just stating that something isnt working for you its not useful to debug.  
@matrix  sorry, but the code breaks which leaves the file corrupted. How about deleteing a few bytes from the end? 
I still think its the hyper_geometric function that fucks up. @pwpiwi has other things to do than looking into this.  I got the suggestion from @blapost code doesnt have this limitiation. (found here: http://crapto1.netgarage.org/)

**Comment by osysltd** [comment]
Nothing as you mention, Chris. Sorry  if I've said something wrong, dear friends! I just wanted to provide feedback that I thought might be useful for us to collaborate. Sorry if  not.

**Comment by iceman1001** [comment]
Great,  @osysltd  would you be so kind and save your nonces (add parameter "w")  and share it here. 
Maybe we can replicate the bug that way.   A problem right now is not being able to replicate it.

[edit]  and now I saw that you did do that earlier. sorry.  forget about this suggestion.

**Comment by matrix** [comment]
Hi @iceman1001, if you tried without my patches and it work please remove my mods,
but if you want to keep it search the bug in what I change, not in the p_hypergeometric() because I don't change nothing in this function.

With my hardware (proxmark rdv2 and mifare classic ev1 card) it work,
let me know.

```
uC: AT91SAM7S512 Rev A
Embedded Processor: ARM7TDMI
Nonvolatile Program Memory Size: 512K bytes. Used: 217142 bytes (41). Free: 307146 bytes (59).
Second Nonvolatile Program Memory Size: None
Internal SRAM Size: 64K bytes
Architecture Identifier: AT91SAM7Sxx Series
Nonvolatile Program Memory Type: Embedded Flash Memory
```

**Comment by iceman1001** [comment]
The thing is, for me it works when it finds the key in the first "batch".
I'm not removing your mods because they are smart and make sence.  I do want it to be stable.
I hear what you say about yr hardware,  I still don't think that is the problem here.  Try another card or (sektor/block) .  The mem bug shows when its not found in the first batch. (or thats what I see)
[edit] yes, you didnt change hyper_Geomentry function I know but that doesnt mean the bug manifests until it come there.

**Comment by matrix** [comment]
But I write that for speedup the cracking when its not found in the first batch :)
With my hardware it work, found ever the key, first or later key is found and cracked.
What's your proxmark version?

I'm trying now one of the hardest sector in my card and I crack it in < 5 minutes.
Please remove my mods, you can start by restore the original "sizes_even" array values,
here https://github.com/iceman1001/proxmark3/blob/master/client/cmdhfmfhard.c#L912-L913
 and re-test.

@osysltd I tried also your nonces.bin and I do not found the key inside (cracking failed)

**Comment by matrix** [comment]
@iceman1001 , try that

```
diff --git a/client/cmdhfmfhard.c b/client/cmdhfmfhard.c
index a6b8bc5..acee853 100644
--- a/client/cmdhfmfhard.c
+++ b/client/cmdhfmfhard.c
@@ -274,7 +274,7 @@ static double p_hypergeometric(uint16_t N, uint16_t K, uint16_t n, uint16_t k)
                        for (int16_t i = K+1; i <= N; i++) {
                                log_result -= log(i);
                        }
-                       return exp(log_result);
+                       return (log_result > 0) ? exp(log_result) : 0.0;
                } else {                        // recursion
                        return (p_hypergeometric(N, K, n, k-1) * (K-k+1) * (n-k+1) / (k * (N-K-n+k)));
                }
```

**Comment by GreatMichaelLee** [comment]
guys, have read all you posted above, looks like, the function of hardnested is broken to me as well from the latest change, it is always generating logging "fail after xxx times" such like that and infinite loop in such a routine.  if you need my nonce file, let me know

**Comment by matrix** [comment]
Hi, could you retry testing from @osysltd patch-4 commit?
Remember to update proxmark firmware after restoring old revision.

Thanks

**Comment by GreatMichaelLee** [comment]
hi, I didn't see any repository from @osysltd  attached to Proxmark3 or there is no osysltd's merge commit on iceman1001 repository network graph?  where is this patch 4 commit located?

**Comment by matrix** [comment]
Ok, so you can use very older commit for exclude all my mods:

git reset --hard 67cd89033c36aade765946cd9f607e787fec7074

**Comment by GreatMichaelLee** [comment]
thanks, I will try that and let you know if this working fine .

**Comment by matrix** [comment]
https://github.com/matrix/proxmark3/commit/869a03c2c6267db16cd1418b9e5f2b9049b9a015

**Comment by iceman1001** [comment]
I've pushed @matrix  latest fix.  
This how it look for me:  http://pastebin.com/FJMqm2zB

**Comment by matrix** [comment]
strange output :)

```
Key Found after testing -2311633482 (2^64.0) out of 13485081692 (2^33.7) keys.
Success! Found 1 keys after 0 seconds
```

**Comment by iceman1001** [comment]
indeed strange output.
Running it several times, it finds some keys. 
its like when it starts collecting next 2000 nonces it doesnt recalc the probabilites correct..
and could be the cause for the strange output.  Pure guessing from my side.

**Comment by iceman1001** [comment]
There could also be some variables like "count", "maximum_states" that gets wrong data after first try.

**Comment by GreatMichaelLee** [comment]
looks still problem, I tried a token which once could be hardnested in this commit, however, nothing logging printed and ten minutes after still nothing there and stuck there. the light is firstly showed on with ACD and C is blinking, however, in 1-2 minutes later, the C is off and AD stick to ON always

**Comment by GreatMichaelLee** [comment]
I just reset to 67cd890, totally different behavior.... light C will be blinking till found the proper data to start 4 thread to do  brute force, however, in the 8690a3c  the light C is immediately OFF and stuck there, looks like ,the routine is running into a error dead loop and cannot jump out with heavy CPU load. er....just my guess from the mingw behavior... @matrix  could you double check what the possible reason? if necessary I could send a nonce file with 67cd890 for my this token.  but not sure it help your debugging or not.

**Comment by matrix** [comment]
@18688994688 you try individually all the commits after 67cd890\* for see if you found the key?
I'm not the same hw as you, @iceman1001 you can do?

**Comment by matrix** [comment]
@18688994688, another version is up

https://github.com/matrix/proxmark3/commit/bd8249afeccb0478d8dbbfb49ed68c6306182f1f

could you retest it ?
Thanks

**Comment by osysltd** [comment]
@matrix 
FYI I was able to recover with pm3 easy hw the most hardened sector key with your commit, looks stable and functional.
Thank you!

**Comment by iceman1001** [comment]
I've pushed @matrix   latest commit.

I'm getting some  "no response from proxmark" after success/fail of key retrival.  I  wonder if the device is still collecting nonces during all time.

**Comment by iceman1001** [comment]
As seen here:  http://pastebin.com/sxR6up1P
First time fails, client doesnt continue,   second attempt is successful.
The number of good bytes increases very fast.  pre-mod by matrix it needed to collect a lot of nonces.

**Comment by matrix** [comment]
Hi @iceman,
there're some bugs not related to my mods, like "no response for proxmark",
"2^-inf", etc...
Please handle as different issue on github/forum :)
Thanks

**Comment by iceman1001** [comment]
Sure,  however the restart for collecting the next 5000 nonces I still see as problem with your mod.

The exit strategies from hardnested code, could be seen as a consequence from changing the accuire_nonces calls with your mod.  Still this current issue has a lot of different problems related to older hardware and hardnested in general (as that code wasnt released either) and I agree this issue should be closed to make things more straightforward.

I'm guessing we get some feedback from @18688994688  @osysltd  soon enough.

**Comment by matrix** [comment]
Yes, you see the same problem with my mods because I'm not solve this bug
with any of my mods.
That's a bug with "green" proxmark, if you test it by hard reset before my
mods you still see it !
I will be happy if one day I can try my mods in a "stable" version of
proxmark for understand better what I need change and what no ...
It's very difficult now understand if my mods are goods or not :|

**Comment by GreatMichaelLee** [comment]
@matrix @iceman1001  I tried the latest push, 2 problems there 1) don't know why the efficiency looks like not good, run one hour with 600K + acquire only got into guessing numbers 2  and 2) the acquiring nonce try give up and hw lost response,   see below screensnap:

Acquired 593600 nonces (22156 / 25000 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 2
Acquired 594048 nonces (22159 / 25000 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 2
Acquired 594608 nonces (22164 / 25000 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 2
Acquired 595056 nonces (22164 / 25000 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 2
Acquired 595504 nonces (22165 / 25000 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 2
Acquired 596064 nonces (22175 / 25000 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 2
Acquired 596512 nonces (22180 / 25000 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 2
Acquired 597072 nonces (22193 / 25000 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 2
Acquired 597520 nonces (22193 / 25000 with distinct bytes 0 and 1). Number of bytes with probability for correctly guessed Sum(a8) > 95.0%: 2
Waiting for a response from the proxmark...
Don't forget to cancel its operation first by pressing on the button
Error: No response from Proxmark.

pm3 -->

**Comment by matrix** [comment]
Hi @18688994688,
You have acquired a lot of nonces (597520) but very few with distinct bytes 0 and 1.
Seems an hardware error related problem.
Try tuning the proxmark with your card before run the attack (hw tune and/or hf tune).
Let me know

**Comment by osysltd** [comment]
@iceman1001 @18688994688 @matrix per my findings, hardened sectors pass well until out of memory exception comes. There are still couple of sectors being constantly welcomed by the exception (RDV2\Easy, different sector\keys).

In the initial @aczid implementation long process of collecting nonces result in almost complete guarantee to get the key. I also remember some discussions on the forums about the key 'vulnerability' to the attack mentioned by @pwpiwi. So in short words to have good probability we need to make a good nonce analysis imho

**Comment by matrix** [comment]
Hi @osysltd,
interesting, could you paste here the link to the forum discussion about this vuln?
Thanks :)

**Comment by osysltd** [comment]
Hi @matrix,
Should be somewhere out here http://www.proxmark.org/forum/viewtopic.php?id=2120 or outside in the other threads. You're always welcome!

**Comment by matrix** [comment]
Ok but I think the best place to request this type of ennancement is a new thread in the proxmark forum.

**Comment by matrix** [comment]
https://github.com/matrix/proxmark3/commit/e0828439bfebdcf16595e7cda76e40e21f4feeb6

**Comment by GreatMichaelLee** [comment]
hi @matrix what does e082843 fix?

**Comment by matrix** [comment]
Hi,
I get one only valgrind error now and the candidates now it's evaluated
only if num_goods_first_bytes > 0.
Could you test it?

**Comment by osysltd** [comment]
Hi @matrix 
Great enhancement, Works very stable, got the hardest key solved with your changes.

**Comment by pwpiwi** [comment]
@18688994688: you don't try hardnested with an old Mifare Classic card, don't you?

**Comment by GreatMichaelLee** [comment]
@pwpiwi what do you mean to old mifare classic card? does it mean to vulnerable for dark side attack card?

**Comment by iceman1001** [comment]
I've open another issue, for something strange that happens in the aquire_nonces function.

**Comment by osysltd** [comment]
@18688994688, yes. Old is also fairly easy guessed by nested.

**Comment by GreatMichaelLee** [comment]
@osysltd Yes, I understood, I am just trying if the old Mifare card could be hardnested or not, however, it could go into getting good bytes number to 4 or 5 stage after one hour running while a sudden 'death' coming up which the client prompts 'Error: No response from Proxmark.'(log pasted above)  then stop working,  this is reproducible and I just wondering what cause this. if this 'no response' issue not happen, the old mifare card could also be hardnested to resolve a key if give it enough hours even it is slowly?

**Comment by pwpiwi** [comment]
No, the old card cannot be hardnested. You can easily see the reason: it doesn't give you enough different nonces because of its broken PRNG.

**Comment by GreatMichaelLee** [comment]
OK, I think so, I do this is just to test the program stabilization(e.g, long run w/o any memory leak) as it will not get any key result and keep running and running,  but looks like it will exit with non response after  about one hour (up to 500K acquiring),  don't know this is related to the code or the hw.

**Comment by pwpiwi** [comment]
What's your hardest key? I came across this one: b9d644b49dfe. Might be 
useful to collect a few test cases.

Gesendet mit AquaMail für Android
http://www.aqua-mail.com

Am 8. November 2016 1:05:29 nachm. schrieb Osys notifications@github.com:

**Comment by osysltd** [comment]
Dear @pwpiwi I would like to share it privately for obvious reasons, please could you share means of direct communication with you?

**Comment by pwpiwi** [comment]
You can send to prolocobup@throwam.com

Gesendet mit AquaMail für Android
http://www.aqua-mail.com

Am 9. November 2016 9:07:14 vorm. schrieb Osys notifications@github.com:

**Comment by osysltd** [comment]
Dear @pwpiwi, done!

**Comment by pwpiwi** [comment]
Received. How long does it take for you to crack these? And mine?

Gesendet mit AquaMail für Android
http://www.aqua-mail.com

Am 9. November 2016 1:43:15 nachm. schrieb Osys notifications@github.com:

**Comment by osysltd** [comment]
Your's haven't tested, but mine hardest key took about a day with testing different known sectors\keys ending up finally with good bytes about 250 and the key was guessed.

**Comment by GreatMichaelLee** [comment]
@iceman1001 @matrix  I've tested a hardended token with iceman's 71ac327 and matrix' e082843(v3) both can crack the key A in very short time (about 2-3 min), however these two got the different behavior on cracking key B. let me explain on the following:  pre-condition is this token will some time prompts auth error or time out, I select ignore it as it maybe the card quality problem like response time performance problem in a stressing attack(my hw tune and hf tune has no problem) and interleave printing the good bits number guessed log between those errors log on screen, the different for these two commits are , for iceman's version, once the program think the good bits number is good enough and try to start the brute force thread, and in the meantime there happen to an auth error encountered, iceman's code will immediately run into a dead loop with continously printing "db # authentication error" very fast and cannot go back to run into starting thread any more, but matrix's code works fine and started the thread for calculating the key.  this is just carried out from my observation, and I am not sure this is a certain pattern or not.  also, I didn't compare your guys code, just FYI and if you have interesting to analysis whether there is any logic hole there. btw: it takes~1300s to crack key B by using matrix v3 code, and thanks, it works the key out and so great!

**Comment by matrix** [comment]
Nice :)
If you put the card to the right distance from antenna all the
errors/timeout message disappear.

Thanks for testing ;)

**Comment by GreatMichaelLee** [comment]
shouldn't it be the token more closer to antenna more better for RF communication? why need a 'distance' to keep away from the 'errror/time out'?  don't understand the tricky, anybody can elaborate? :)

**Comment by iceman1001** [comment]
There are posts on the forum explaining this.

**Comment by osysltd** [comment]
@18688994688 per my findings, Easy hw version stopped throwing timeouts when @iceman1001 applied change to disable the tracelogging on device side during nonce acquiring. Hope this helps.

**Comment by GreatMichaelLee** [comment]
Looks like this bug could be resolved?  I tried matrix V5, it works perfect!  if @iceman1001 could pull this commit?

**Comment by iceman1001** [comment]
I don't know,  the previous v4 does a better job on one of my "hard" keys.   

This key: 26940b21ff5d

**Comment by matrix** [comment]
@iceman1001 retry from my last commit, it's not v5

**Comment by iceman1001** [comment]
It looks good with @matrix commits,  I'm fiddleing with finding a "good" estimate when to call the brute_force.  @matrix calls it every 5000nonces now.   But on simple keys (if thats what we call them)  already around 2000-3000 nonces is enough to be successfull.   The number of good first bytes goes high very fast.  Still its a guess.  On my test tag, I've gotten down to 18seconds finding a key.

**Comment by matrix** [comment]
Hi @iceman1001, I think the same before finding another tag to test.
Some tags release a sufficient number of good bytes more slowly,
so I chose a middle ground to obtain a good performance results in both cases.

@pwpiwi there're others improvement we can do in the analysis of the nonces collected ? if the keyspace can be reduced would be great :)

**Comment by iceman1001** [comment]
I'm closing this one,  @matrix  mods works nice now with hardnested.
