### ISSUE TITLE
hf mf hardnested r crashes on pthread_join (Windows)

### ISSUE THREAD

**Issue by vasily-z** [iceman1001/proxmark3#54]
Client compiled according to Windows guide. System runs Windows 10 (32). Client seems to crash on pthread_join(threads[i], 0); (Line 1716 of client/cmdhfmfhard.c file).
Tested on two machines.

**Comment by menshiyun** [comment]
try newer gcc version

**Comment by iceman1001** [comment]
Did you compile using GGC version 4.8 or bigger?

**Comment by vasily-z** [comment]
Hi! I compiled it with GCC, which comes with QT 5.6.1 (as recommended). I am new to this, but it seems that the version is 4.9.2. I am trying to update GCC, but it not very straightforward on windows...

**Comment by osysltd** [comment]
`Thread model: posix, gcc version 4.9.2 (i686-posix-dwarf-rev1, Built by MinGW-W64 project)`
Try to use the following environment and please let us know the results: http://download.qt.io/archive/qt/5.7/5.7.0/qt-opensource-windows-x86-mingw530-5.7.0.exe

**Comment by menshiyun** [comment]
You can use mingw-w64-gcc version 6 in msys2.
This is how I build the PM3 environment.
https://github.com/menshiyun/proxmark3/blob/local/ENV_en.md
(Forgive me for my tough English)
You can change the 4th step to iceman's fork.

**Comment by vasily-z** [comment]
@menshiyun thank you! Your solution is simple and it helped.

**Comment by GreatMichaelLee** [comment]
@vasily-z I use @menshiyun 's setup all the way and works perfect :) this guy is a perfect style holic :)
