### ISSUE TITLE
mfdes broken?

### ISSUE THREAD

**Issue by ralik** [iceman1001/proxmark3#6]
On latest commit 57850d9
Getting following errors in: mfdes
unknown command:: 0x072d, 0x072e, 0x072a...

**Comment by iceman1001** [comment]
Usually when you get the "unknown command" message,  you have mixed up firmware and client software from different forks/branches.  Like fullimage from my fork and using pm3 master client.

I suggest you make sure you have compiled/flashed and use fullimage.elf & proxmark3.exe from the same fork.

**Comment by ralik** [comment]
Sorry... I forgot to flash from original repo...
Fixed.

**Comment by iceman1001** [comment]
Excellent,  
I will close close this one then.
