### ISSUE TITLE
AppVeyor Build

### ISSUE THREAD

**Issue by KitsuneDev** [iceman1001/proxmark3#73]
Hi.
@iceman1001, just a little tip, why don't you create an appveyor build for windows?? Here is an idea: http://stackoverflow.com/a/26634443/6158547

**Comment by iceman1001** [comment]
I did think about it when I added the TravisCI and CoverityScan. At that time I didnt find support for Mingw.
Which your link suggest works now.  If you have done an appveyor.yml file before, feel free to add it to the project.

**Comment by KitsuneDev** [comment]
Ok, finishing it...

**Comment by KitsuneDev** [comment]
@iceman1001 Sorry, I actually don't have it

**Comment by GabrielTK** [comment]
@iceman1001 If you want, you can host it on my CI. Just add me as a contributor and I'll set it up for you 😄

**Comment by iceman1001** [comment]
Sorry, I'm not following :)  I've added a appveyor.yml file to the fork. However I lack the knowledge of configuring it correct.

**Comment by iceman1001** [comment]
one step closer.  apparently downloading thirdpart libs is hard on appveyor

**Comment by iceman1001** [comment]
Another step closer with @akelios additions to the appveyour.xml ..

**Comment by iceman1001** [comment]
With @merlokk 's config it works fine.
