### ISSUE TITLE
LF Search no longer detects Viking Tags properly.

### ISSUE THREAD

**Issue by phiberx** [iceman1001/proxmark3#82]
When doing a LF Search, a Viking tag is not being detected correctly anymore.

It shows "Valid EM410x tag found" instead but with no tag information.

**Comment by iceman1001** [comment]
Yes, I'vent finished merging all 4x05 changes by marshmellow yet.  Pretty soon.  if you use the latest release v1.6.9 you will not have a problem meanwhile.

**Comment by phiberx** [comment]
Thanks Iceman! Awesome work nonetheless!

**Comment by iceman1001** [comment]
the `lf search` should work now again.
