### ISSUE TITLE
client compiler warnings in proxmark3.h and proxmark3.c 

### ISSUE THREAD

**Issue by SpaceTeddy** [iceman1001/proxmark3#83]
const char const *get_my_executable_path(void)
in proxmark3.h and proxmark3.c gives many compiler warning:
warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier]

change to "const char *get_my_executable_path(void)" fix it.

**Comment by iceman1001** [comment]
Good catch @SpaceTeddy   thanks!   I've pushed it.
