### ISSUE TITLE
EMV command

### ISSUE THREAD

**Issue by mastahofdesastah** [iceman1001/proxmark3#94]
Since the last updates, the EMV commands doesen't work anymore.

After i uncomment
APP_CFLAGS += -DWITH_EMV
COMMON_FLAGS += -DWITH_EMV

and compile it, any EMV commands gives me
#db# unknown command:: 0x070X

my fault?

**Comment by iceman1001** [comment]
Did you flash the device?

**Comment by mastahofdesastah** [comment]
Seems that i didn't flash it correctly, thx for the hint.
You can close the issue

Edit:
Get this error when i try to compile the FW
obj/emvcmd.o: In function `EMVSelectPPSE':
emvcmd.c:(.text.EMVSelectPPSE+0x4): undefined reference to `emv_selectPPSE'
collect2: error: ld returned 1 exit status
Makefile:104: die Regel für Ziel „obj/fullimage.stage1.elf“ scheiterte
make: *** [obj/fullimage.stage1.elf] Fehler 1
